compatibility_date = "2021-11-01"
compatibility_flags = []
name = "vavite-testbed"
route = ''
site = {bucket = "dist/bundled/static", entry-point = "dist/bundled"}
type = "javascript"
usage_model = ''
workers_dev = true
zone_id = ''

[build]
command = "DEPLOY_TARGET=cfw npx vite build"

[build.upload]
format = "service-worker"
